version: '2'
services:
  names:
    container_name: names
    image: ghcr.io/nightwire/docker-names:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/hosts:/mnt/hosts
    restart: unless-stopped